version: '3.8'

services:
  qrcgen:
    container_name: qrcgen
    network_mode: lefina-dev
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/qrcgen-api
      - qrcodes:/app/qrcgen-api/qrcodes
    restart: always
    ports:
      - 5005:5005
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: npm start

volumes:
  qrcodes: